### ISSUE TITLE
Documentation should state more clearly that playsinline is only for mobile

### ISSUE THREAD

**Issue by sedubois** [vidstack/player#1005]
### URL:

https://www.vidstack.io/docs/player/getting-started/installation/web-components?provider=hls&styling=tailwind-css

### Describe:

Documentation on playsinline does not make it clear enough that it only applies to mobile devices. At least in my tests, on desktop the video plays inline instead of going full screen, even if playsinline is not set.

The documentation does refer to the fact that it applies to mobile, but only with a single "mobile" word hidden in the latter part of the explanation (_"If you do not set playsinline, the video will launch in fullscreen on play in all mobile browsers"_), which I had been missing on first read and led to some time wasted. The confusion also came from the fact that the `playsinline` keyword itself makes it sound like it applies to all devices, not only mobile.

I would propose to update the documentation to something such as the following:

```diff
- 10. Playsinline (Optional)
+ 10. Playsinline (Optional - mobile only)

- The playsinline property will indicate that video content should be played inline, rather than launching the video in fullscreen mode on play. ...
+ The playsinline property will indicate that video content should be played inline on mobile, rather than launching the video in fullscreen mode on play. ...

Important to note, we normalize the playing inline behaviour across all mobile browsers. If you do not set playsinline, the video will launch in fullscreen on play in all mobile browsers, not just iOS Safari where the attribute is accepted.

+ The playsinline property only applies to mobile. It does not affect desktop playback behaviour.
```

### Environment:

- Framework: Web Components, Tailwind CSS
- Meta Framework: Ruby on Rails
- Node: 20
- OS: macOS Sonoma 14
- Browser: Safari 17

**Comment by mihar-22** [comment]
Thanks for report! Ye I can see that it's not clear about being mobile only. Just a heads up that you can raise docs issues in the future at our [site repo](https://github.com/vidstack/site). Here's the [file in question](https://github.com/vidstack/site/blob/main/src/docs/installation/partials/set-playsinline.mdx).

You're raising an interesting point here on whether this behaviour should apply to desktop too. I applied it to mobile browsers only (actually all touch devices), because that's where the `playsinline` attribute natively takes place on iOS `<video>`. I think it may lead to unexpected behaviour if we apply it to desktop too.

Maybe we can extend it to accept additional values beyond a `boolean`. Something like `boolean | 'pointer-fine' | 'pointer-coarse' | 'any'`? I'm trying to model it after the [pointer CSS media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer) which we use under the hood to detect touch. We could instead do `'mobile' | 'desktop'` but I don't think it's entirely accurate and the definitions of mobile/desktop are quite loose.

I'll sit on this for a little to give time for feedback. If you have any thoughts love to hear it. If there was something you were trying to accomplish then sharing it might help us make a decision here.

**Comment by sedubois** [comment]
> Just a heads up that you can raise docs issues in the future at our [site repo](https://github.com/vidstack/site)

FYI the [issue templates](https://github.com/vidstack/player/issues/new/choose) suggest to open documentation issues in this repo.

> I think it may lead to unexpected behaviour if we apply it to desktop too

I understand, in my case I came from the opposite approach: the name `playsinline` makes it sound like it will play inline, full stop, regardless of the platform, screen size or whatever; and that its absence will do the opposite: inline playback will be prevented (force switch to full screen when clicking play). But it is beyond my competence to say if/how to resolve the discrepancies between the varying expectations of library users such as myself, naming conventions, and web standards (or lack thereof).

The idea of resolving this with some sort of finer-grained config sounds reasonable. It would be great if it could be responsive, that's what I need (i.e. regardless of the kind of device, force the playback to go full screen if the container is small, but allow playing inline when it becomes big enough). In other instances such as when playing pure audio, I want on the contrary to always play inline regardless of screen size. Our player needs to manage both audio and video and so must be able to combine such requirements. (We are currently working around the situation using Javascript.)

And the other part of the solution is to make the docs reflect more accurately whatever is going on.

**Comment by mihar-22** [comment]
I've added an additional bolded statement that playsinline is mobile only in the docs. For now, we won't extend the behaviour of playsinline to desktop but happy to explore it again soon under a new issue.
