### ISSUE TITLE
Delegate error on HLS stream

### ISSUE THREAD

**Issue by sdiama** [vidstack/player#1041]
There is a "weird" issue on the player when playing HLS stream. 
On random users and on random times for each user, the player is not working, and the following errors are logged on the console.log.
![Screenshot 2023-12-09 150537](https://github.com/vidstack/player/assets/4703113/fe85ba24-c11f-4c64-b228-b092d2cc7a98)

The player does not work even after multiple page reloads, cache clears etc. Sometime in the future, starts working again, until the next time the error reoccurred!
I have tested the issue on Linux/Windows 10/Windows 11/Android phone with multiple browsers and this "random" behavior always comes up.

The integration of the player is using simple instructions given at the documentation (https://www.vidstack.io/docs/player/getting-started/installation/cdn?provider=video&styling=default-layout)

I have tested with two different streams, streamed from two different platforms, without any difference in behavior. Meanwhile, the streams are working fine on every other player I tested them, with.

**Comment by mihar-22** [comment]
Thanks for reporting! Strange issue and I’ll try to see what I can find tomorrow. My initial hunch is that the CDN is caching and returning the incorrect chunks. It might be because we’re not specifying an exact version? I’m curious if you do whether the issue stops (e.g., changing ^1.0.0 to 1.9.2 in the URL).

**Comment by sdiama** [comment]
Indeed, changing ^1.0.0 to 1.9.2 or 1.9.1 (didn't try other versions) the issue disappeared but... I'm not sure if it's just working fine now and in the future the error will emerge again.
Right now, I leave the CDD version of the vidstack script to 1.9.2 and I'll monitor for the error.

**Comment by mihar-22** [comment]
Found the issue. We mangle properties when building our distribution files. This process was never saved across build so we could end up with similar chunks with different mangled properties. I'll be releasing a fix shortly which should resolve this happening again. It will be safe to go back to `^1.0.0` instead of a fixed version after the `1.9.3` release.
