### ISSUE TITLE
SAFARI : Unexpected token '='. Expected an opening '(' before a method's parameter list

### ISSUE THREAD

**Issue by 9267aakashsharma** [vidstack/player#1114]
### Current Behavior:
Using vidstack player is not working on old safari browsers (<14.1). The same issue is mentioned here as well - https://stackoverflow.com/questions/60026651/safari-unexpected-token-expected-an-opening-before-a-methods-paramet

This is happening with all new libraries which use new way of declaring private and public members in class constructor() method. Which is not supported in older safari versions. (<14.1)

There is a solution mentioned on stackoverflow, but that requires to either patch this package, or using babel plugin. I tried both in my Next.js project. But none of it seems to work.

### Expected Behavior:
Add support for older browsers.

### Steps To Reproduce:
Try running react / next build version of video player in safari browser with <14.1 version

### Environment:
- Framework: React
- Meta Framework: Next.js
- Node: 16.0.0
- Device: iPhone@13
- OS: iOS@14
- Browser: Safari@13

**Comment by mihar-22** [comment]
As a library we have to publish a modern bundle so that users can decide for their application what is right. Your app bundler, in this case Next.js, is responsible for matching your target browsers and polyfilling accordingly. Recommend trying the [Next.js browserslist configuration](https://nextjs.org/docs/architecture/supported-browsers#browserslist).
