### ISSUE TITLE
Youtube: video title and copy link button appear on mobile devices

### ISSUE THREAD

**Issue by vkgencer** [vidstack/player#1179]
### Current Behavior:

Hello,

I use youtube with default theme. after starting and stopping the video in simulator or native devices, youtube video title and youtube link copy button become visible.

The same happens in the demos at https://github.com/vidstack/examples.

### Anything Else?

![image](https://github.com/vidstack/player/assets/5902234/aee6f954-c9eb-46b2-bfe3-25594a88febd)
![vidstack](https://github.com/vidstack/player/assets/5902234/e5d53606-ac2a-4379-8f9f-64c681ebceff)

**Comment by zerowu49** [comment]
Also had same issue, tried to hide it like this [StackOverflow](https://stackoverflow.com/questions/18342536/how-to-hide-the-bar-at-the-top-of-youtube-even-when-mouse-hovers-over-it)  way but they just manipulating the CSS by zooming & zoom out the container. This solution doesn't work well on fullscreen mode. YouTube has **showinfo** parameter on the URL, but already deprecated. Looks like hiding the title could be tricky to be done since this info comes from the native Youtube Embed. Need to find way to use Vidstack API to force their control over Youtube control.

**Comment by mihar-22** [comment]
There’s no real proper way to hide this info, we use a CSS height hack but it doesn’t seem to always hold up depending on size and aspect ratio. Not much we can do unfortunately.

**Comment by Leftium** [comment]
> There’s no real proper way to hide this info, we use a CSS height hack but it doesn’t seem to always hold up depending on size and aspect ratio. Not much we can do unfortunately.

I was able to tweak the CSS height hack to work with most sizes and aspect ratios, notably vertical videos.
- The blue box is the video player frame. Normally YouTube will not overflow outside this region.
- YouTube videos were set to transparent and overflow visible to show how the hack works.
- The videos are centered, so if there is a slight mismatch they will still show (with a little bit of letterboxing or cropping).

![image](https://github.com/user-attachments/assets/f1d4f207-d177-4ba1-a42a-e81f55174136)

The only downside is you must specify if the video is in a vertical aspect ratio.
- Is the youtube video vertical? Is the video player vertical?
- (Worse case scenario: allow user to toggle "vertical mode" when mismatched):
- The leftmost video is similar to how Vidstack currently handles vertical videos.

![image](https://github.com/user-attachments/assets/c9ea4b16-b831-4d84-8f1b-3671113df703)

I have to look into how Vidstack removed YouTube branding in fullscreen mode, but this hack can probably be applied there, too.
