### ISSUE TITLE
Custom Keyshortcuts

### ISSUE THREAD

**Issue by LiReNa00** [vidstack/player#1187]
I'm experiencing an issue with custom key shortcuts in my project. According to the documentation, I've implemented custom key shortcuts to trigger specific functions. However, I'm encountering two problems:

- The custom key shortcut function is being called twice when the key is pressed. For example, if I have a function that toggles a state between false and true based on its previous state, pressing the assigned key causes it to toggle twice (from false to true and back to false).

- The default key shortcuts are not being overridden by the new custom ones that are defined. It seems like the default shortcuts are still active and not replaced by the custom ones.

### Steps To Reproduce:
```jsx
<MediaPlayer
  ref={playerRef}
  src={src}
  keyShortcuts={{
    ...MEDIA_KEY_SHORTCUTS,
    ambient:{
      keys:['a'],
      callback(event){
        setAmbient((prevAmbient) => !prevAmbient)  
      }
    },
    bigseek:{
      keys:['Shift+ArrowLeft', 'Shift+ArrowRight'],
      callback(event){
          const direction = event.key === 'ArrowLeft' ? -1 : 1;
          const newTime = playerRef.current.currentTime + (direction * 90);
          playerRef.current.currentTime = newTime;     
      }
    }
  }}
>
```

### Environment:
- Framework:React
- Meta Framework: Next.js
- Vidstack version: 1.10.9

**Comment by mihar-22** [comment]
I'll be updating the docs on this but two things:

1. The order is important as the first matched takes precedence (it will be triggered rather than a later shortcut). So put `...MEDIA_KEY_SHORTCUTS` _after_ your custom shortcuts.

2. The `callback` is deprecated in the latest version but it's important to note it's fired for both key up and key down (hence twice). The latest has two separate callbacks `onKeyUp` and `onKeyDown`.

**Comment by LiReNa00** [comment]
oh I see, here I was thinking it was bug 😓thanks!!
