### ISSUE TITLE
Clips are quite glitchy

### ISSUE THREAD

**Issue by lirena00** [vidstack/player#1250]
### Current Behavior:

Clips are quite glitchy but this happens in few cases like when I try to pause a clip it starts from 0 once again and sometimes they just don't end and sometimes it starts from somewhere else instead of expected time and sometimes the timestamp just freezes.

### Steps To Reproduce:
I am using default stuff that is provided in the docs not anything custom from my own side

### Environment:

- Framework: React
- Meta Framework: Next.js
- Vidstack version: 1.11.6

### Anything Else?
one of the examples
https://aniray.vercel.app/clip/10165?episode=1&s=553&e=627
![image](https://github.com/vidstack/player/assets/92094239/fcc3ae65-63c5-4e24-850f-fba49d11bd83)

**Comment by LiReNa00** [comment]
it was issue with storage which is bad on my part sorry for this

**Comment by LiReNa00** [comment]
previously I thought probably mediastorage isinterfering with it so I closed the issue and when I did it without using mediastorage it was working fine and several gltiches were resolved but still few issues remains such as 
not able replay the clip (if it's replayed it starts playing from 0:00 instead of provided clip timestamps and moreover progress bar and timestamps gets stuck

https://aniray.vercel.app/clip/10165?episode=1&s=553&e=627
link is still same as before

![image](https://github.com/vidstack/player/assets/92094239/b8db2b25-cea1-46ae-ae8e-c3d91cad5cd2)

**Comment by mihar-22** [comment]
Sorry for the delay as I've been busy. I can't repro this so I'll have to close. The provided link no longer works either. I'll require a proper [repro](https://github.com/vidstack/player/blob/main/.github/REPRO.md) to debug this properly. Happy to reopen when provided. Thanks!!
