### ISSUE TITLE
how to modify the request headers?

### ISSUE THREAD

**Issue by engAmirEng** [vidstack/player#1261]
I'm using hls and I want to send the `authorization` header to the server for each request, how is it possible to do that?

**Comment by mihar-22** [comment]
This isn't an issue, in the future please open a discussion on GitHub or a help post in our Discord channel. I also don't know what framework you're using so provide more info when opening issues, don't be lazy otherwise I might close in the future. 

You need to [configure the HLS instance](https://www.vidstack.io/docs/player/api/providers/hls?styling=default-theme#configuring):

```ts
provider.config = {
  xhrSetup: (xhs, url) => {
    xhr.setRequestHeader("Referer", "https://vidmoly.to/");
  }
}
```
