### ISSUE TITLE
[BUG] Special case with preferNativeHLS: true and load: play

### ISSUE THREAD

**Issue by fogrye** [vidstack/player#1307]
### Current Behavior:

IOS Safari with preferNativeHLS enabled and load strategy `play` creates video element without source and video just stuck loading. Load strategy `idle` works fine.

### Expected Behavior:

Load strategy `play` doesn't break playback.

### Environment:

- Framework Angular

**Comment by mihar-22** [comment]
Seems to work as expected but it can be an issue with the HLS playlist or encoding itself when it doesn't. 

I found it doesn't work with our test files but it works with our Mux stream. I'll ping back here if I figure out what the issue is. Since this isn't an issue with the player itself I'll close for now.
