### ISSUE TITLE
Playback Quality Support

### ISSUE THREAD

**Issue by mihar-22** [vidstack/player#19]
## Tasks

Design and implement an interface to support getting/setting `playbackQuality` across providers.

## API

**Player API**

- `playbackQuality: string`
- `playbackQualities: string[]`

**Media Events**

- `playback-quality-change`

**Media Request Events**

- `media-playback-quality-change-request`

**Important** 

- `playbackQuality` can only be set to a valid value in `playbackQuality`.
- What to do if playback quality is not supported?

## References

- https://github.com/vime-js/vime/blob/master/core/src/components/core/player/PlayerProps.ts#L268-L284
- https://github.com/vime-js/vime/blob/master/core/src/components/providers/MediaProvider.ts#L23-L24
- https://github.com/vime-js/vime/blob/master/core/src/components/providers/hls/hls.tsx#L247-L254
- https://github.com/vime-js/vime/blob/master/core/src/components/providers/dash/dash.tsx#L303-L330

**Comment by danestves** [comment]
Is there any ETA about this one? Is the only component that I need to migrate from `plyr` to `vidstack` using React 🙌

**Comment by mihar-22** [comment]
Hey @danestves! Feature parity work starts mid-to-end next week. We can prioritize `playbackRate` and `playbackQuality` before the rest of the tasks as I've been asked about them a few times. Hope that works :)

**Comment by danestves** [comment]
Awesome! Will look for it and at a later date will look for this https://github.com/vidstack/player/issues/74 🥳  thanks for the response!

**Comment by danestves** [comment]
Just want to drop this here, we moved from `plyr` to `@vime` because it was more easy to implement, we have put everything inside the player and made a custom menu settings that has quality selector support. So, based on the code from `vidstack` we can implement the rest of the stuff easily and adding quality support will make move our code directly to `vidstack` without any problem.

![](https://user-images.githubusercontent.com/31737273/215348782-89a2c230-ad84-4c05-ae96-e937e392fbc0.png)

We will look forward to any changes on this proposal and thank you so much!

**Comment by iDVB** [comment]
@danestves Would you mind sharing your player code on how you got this quality menu to work? We're looking to do the same.

**Comment by dennisspohr** [comment]
Same question like @iDVB - is there any example somewhere how to implement the quality-feature in the player-menu? I can't find anything.

**Comment by mihar-22** [comment]
Hey @dennisspohr!

We don't have a menu component at the moment but most users are using Radix to fill in the gap for now. You can find our documentation for playback quality [here](https://www.vidstack.io/docs/player/core-concepts/quality) which you'll need to wire it up to your own menu.
