### ISSUE TITLE
Airplay Not Working in 4.0

### ISSUE THREAD

**Issue by Layendan** [vidstack/player#790]
### Current Behavior:

Clicking airplay in macos safari player does not cast to appletv.

### Expected Behavior:

Video plays on TV instead of browser when selecting another source to cast to.

### Steps To Reproduce:

1. On macos safari (maybe ios as well) click airplay and select an appletv to cast video to
2. Airplay icon will change to selected source
3. Screen will flicker between video and casting to tv screen
4. Video will still play on original computer instead of selected source

### Environment:

- Framework: Svelte
- Meta Framework: SvelteKit
- Node: 19.6.0
- Device: Mac M1 2020
- OS: MacOS@13.1
- Browser: Safari@16.2

### Anything Else?

This was broken in version 4.0 since it worked correctly in version 3.3.

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/46062388/222954761-3320ee0c-8704-489d-900e-fbef438acdc5.png"> How it should appear _(ss from 3.3)_

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/46062388/222955027-88d6c1ec-a995-4eef-8558-6188ee384679.png"> How it actually appears _(ss from 4.1)_

**Comment by mihar-22** [comment]
Okay so the problem here is that we prefer using `hls.js` over the native engine for various reasons, which sets a `blob:..`  URL on the `<video>` element. When you activate AirPlay it'll send the source over (the blob) and won't recognize it, hence playback will fail and resume in the browser.

You can now in `0.4.2` suggest you'd prefer the native HLS engine like so:

**HTML**

```html
<media-player prefer-native-hls>
```

**React**

```jsx
<MediaPlayer preferNativeHLS>
```
