### ISSUE TITLE
Vue3 issue: autoplay, playsinline

### ISSUE THREAD

**Issue by BuffMcBigHuge** [vidstack/player#994]
The following simplified code plays videos in my Vue3 app:

```
<div v-for="(file, index) in files" :key="index">
  <media-player v-if="file.filetype.includes('video')"
         class="cursor-pointer"
         @click="selectFile(file)"
         :style="`width:100%;height:100%;`"
         :ref="`video_${index}`"
         :title="`video_${index}`"
         :src="file.url"
         loop
         muted
         playsinline
         autoplay >
     <media-provider />
  </media-player>
</div>
```

For some reason, `autoplay` and `playsinline` particularly aren't triggered on mobile and have no effect. Simply changing `<media-player>` to `<video>` and removing `<media-provider>` as a native HTML5 video seems to solve the issue.

Tested on iOS and Android (Chrome).

```
    "vidstack": "^1.5.1",
    "vue": "^3.3.7",
```

**Comment by mihar-22** [comment]
Thanks for reporting! Found the issue finally, it was internal. Fix rolling out soon today in `1.5.3`.

**Comment by BuffMcBigHuge** [comment]
Hey @mihar-22, it's still not working correctly with version `1.5.5`.

<img width="479" alt="Screenshot 2023-11-13 at 11 17 02 AM" src="https://github.com/vidstack/player/assets/20268348/329af9e3-458e-4cf6-ad97-a4dea58247b3">

Switching to the `<video>` tag works correctly.

**Comment by mihar-22** [comment]
There should be no difference with programmatically calling `play()` like we do under the hood, and `autoplay` attribute on video element. Other popular players like video.js do the same. We do this to know when autoplay fails. The error you're seeing is expected due to [autoplay policies](https://www.vidstack.io/docs/wc/player/api/autoplay#autoplay-policy).

When you're testing with the `<video>` element are you by chance setting `muted`? Is there a difference with how you're setting both up?
